version: '3'

services:
  lib:
    build: .
    depends_on:
      - redis
    environment:
      - DOCKER=True
      - PIP_NO_BINARY=h5py
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache:/home/nens/.cache  # shared cache
    command: tail -F anything
  redis:
    image: redis:3-alpine
